spring:
  application:
    name: taskmaster

  # Connect to Docker Postgres image
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  
  # Align database schema with our code
  jpa:
    hibernate:
      ddl-auto: update