spring:
  application:
    name: taskmaster

  # Connect to Docker Postgres image
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/postgres # Spring Boot
    url: jdbc:postgresql://db:5432/postgres # Docker Compose
    username: postgres
    password: postgres

  # Align database schema with our code
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.andredavcev.taskmaster: INFO
