POST {{host}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "Andre",
    "lastname": "Davcev",
    "email": "andre.davcev@gmail.com",
    "password": "password1234",
    "role": "USER"
}
