name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  nx-ci:
    uses: andre-davcev/fantasia-super-app/.github/workflows/nx-ci.yml@main

  deploy:
    runs-on: ubuntu-latest
    needs: nx-ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Fantasia
        run: |
          npm ci
          npx nx build fantasia-angular
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FANTASIA_C9431 }}'
          channelId: live
          projectId: fantasia-c9431
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  downmerge:
    uses: andre-davcev/fantasia-super-app/.github/workflows/downmerge.yml@main
    needs: deploy
